---
title: "Comparing Delay Types - Pivot"
subtitle: "Unit 2 Stretch Task"
author: "Mitzi Vite"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests
import io
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))

# Cleaning the data 
df = df.with_columns(
    pl.when(pl.col("month") == "n/a").then(None).otherwise(pl.col("month")).alias("month"),
    pl.when(pl.col("num_of_delays_late_aircraft") < 0)
      .then(None)
      .otherwise(pl.col("num_of_delays_late_aircraft"))
      .alias("num_of_delays_late_aircraft"),
    pl.when(pl.col("minutes_delayed_nas") < 0)
      .then(None)
      .otherwise(pl.col("minutes_delayed_nas"))
      .alias("minutes_delayed_nas")
)

df = df.with_columns(
    pl.col("month").str.replace("Febuary", "February").alias("month")
)

minute_cols = [col for col in df.columns if col.startswith("minutes_delayed")]
num_of_cols = [col for col in df.columns if col.startswith("num_of")]

df = df.with_columns([pl.col(col).cast(pl.Float64, strict=False) for col in num_of_cols])
df = df.with_columns([pl.col(col).fill_null(pl.col(col).median()) for col in minute_cols])
df = df.with_columns([pl.col(col).fill_null(pl.col(col).mean()) for col in num_of_cols])

df.head(3)
```

## QUESTION 1
1. __Which delay is the worst delay? Keep working with the cleaned dataset you created in the previous task. Compare the proportion of flights delayed due to Carrier, to Security, and to Late Aircraft. Show this comparison in a Chart and a Table. Describe your results.__

_The graph shows that Late Aircraft is the worst cause of delays across all airports, followed by Carrier delays. This pattern is consistent across all 7 airports. Security delays are almost nonexistent and barely visible in the graph due to how rarely they occur. San Diego has the highest proportion of delays overall, while Atlanta has the lowest, making it the most reliable airport among the three delay types analyzed_
```{python}

df = df.with_columns(
    (pl.col("num_of_delays_carrier") / pl.col("num_of_flights_total")).alias("proportion_delays_carrier"),
    (pl.col("num_of_delays_security") / pl.col("num_of_flights_total")).alias("proportion_delays_security"),
    (pl.col("num_of_delays_late_aircraft") / pl.col("num_of_flights_total")).alias("proportion_delays_late_aircraft")
)

result = df.group_by("airport_name").agg(
    pl.mean("proportion_delays_carrier").alias("avg_proportion_delays_carrier"),
    pl.mean("proportion_delays_security").alias("avg_proportion_delays_security"),
    pl.mean("proportion_delays_late_aircraft").alias("avg_proportion_delays_late_aircraft")
).sort("avg_proportion_delays_carrier", descending=True)

result.head()

long_result = result.unpivot(
    index = "airport_name",
    on = ["avg_proportion_delays_carrier", "avg_proportion_delays_security", "avg_proportion_delays_late_aircraft"],
    variable_name = "delay_type",
    value_name = "proportion_delayed"
)
long_result = long_result.filter(pl.col("airport_name") != "")

long_result = long_result.with_columns(
    pl.col("delay_type").str.replace("avg_proportion_delays_carrier", "Carrier")
    .str.replace("avg_proportion_delays_security", "Security")
    .str.replace("avg_proportion_delays_late_aircraft", "Late Aircraft")
)
print(long_result)

(
  ggplot(long_result.to_pandas(), aes(x="airport_name", y="proportion_delayed", fill="delay_type"))
  + geom_bar(stat="identity", position="dodge")
  + coord_flip()
  + ggsize(800, 400)
  + labs(
    title="Proportion of Delayed Flights by Delay Type and Airport",
    x="Airport",
    y="Average Proportion of Delayed Flights"
  )
)
```

2. __Create another chart that shows the proportion of delays for each reason (Carrier, Security, and Late Aircraft) across all 7 airports. Describe your results.__