---
title: "Client Report - Famous Names"
subtitle: "Unit 1 Task 3"
author: "Mitzi Vite"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```



## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__Make a new column that represents the total number of babies with your name for only those states in which you have lived. (If you have only ever lived in one state, pick at least one other state so you get practice summing across columns). Make a graph displaying that total for your name over time.__

_In the plot below, I showed the total number of babies named Mitzi in Utah and Idaho from 1940 to 1985. I focused on this range because the name was only used during these years. The graph shows that Mitzi was not a very common name, but it had some increases over time. The dashed red line represents the average number of babies named Mitzi during this period._

```{python}
# Q1
df.columns
df.head()
babies_with_name = (
    df.filter(
        (pl.col("name") == "Mitzi")
        & (pl.col("year") >= 1940)
        & (pl.col("year") <= 1985)
    )
    .select([
        pl.col("year"),
        pl.sum_horizontal(["UT", "ID"]).alias("total_babies")
    ])
    .sort("year")
)

mean_total = babies_with_name["total_babies"].mean()
plot_data = babies_with_name.to_dict(as_series=False)

babies_with_name.head()

(
    ggplot(plot_data, aes(x="year", y="total_babies"))
    + geom_line(color="#1b6ca8", size=1.3)
    + geom_point(color="#1b6ca8", size=1.8)
    + geom_hline(yintercept=mean_total, linetype="dashed", color="#c0392b")
    + labs(
        title="Total Babies called Mitzi in UT + ID",
        x="Year",
        y="Total Babies"
    )
)

```


## QUESTION 2

1. __Let's look at a name that is special for members of the church: Brigham. For each year, calculate what proportion of babies named Brigham were born in Idaho and Utah? Make a graph displaying the proportion over time.__  

_The graph displays the proportion of babies named Brigham who were born in Utah and Idaho compared to the total number of babies named Brigham in the United States each year. Values closer to 1 mean that most babies with this name were born in those two states.

The graph also shows a decline between the late 1980s and early 1990s. Since Brigham is a less common name, small changes in the number of babies with this name can create large changes in the proportion. In more recent years, the proportion has decreased slightly, suggesting the name may be becoming less concentrated in Utah and Idaho._

```{python}
# Q2
brigham_name = (
    df.filter(pl.col("name") == "Brigham")
    .select(
        pl.col("year"),
        (pl.col("UT") + pl.col("ID")).alias("Total_UT_ID"),
        pl.col("Total")
    )
)
brigham_name = brigham_name.with_columns(
    (pl.col("Total_UT_ID") / pl.col("Total")).alias("proportion_UT_ID")
)

plot_brigham_name = brigham_name.select(["year", "proportion_UT_ID"]).to_dict(as_series=False)

(
    ggplot(plot_brigham_name, aes(x="year", y="proportion_UT_ID"))
    + geom_line(color="#1b6ca8", size=1.3)
    + geom_point(color="#1b6ca8", size=1.8)
    + labs(
        title="Proportion of Babies Named Brigham in UT + ID",
        x="Year",
        y="Proportion"
    )
)

```

<!-- Make sure at least one of your charts includes reference marks!! -->

## QUESTION 3

1. __Consider doing some data validation. For the name David, calculate a sum of all 50 states and District of Columbia for each year. Now compare that total to the value in the 'Total' column. In which years, if any, do they not agree?__

_The validation did not show any years where the calculated total was different from the Total column. This means that for the name David, the sum of all 50 states and the District of Columbia matches the Total column for every year in the dataset._

```{python}
# Q3
validation = (
    df.filter(pl.col("name") == "David")
    .with_columns(
        pl.sum_horizontal(pl.exclude(["name", "year", "Total"])).alias("calculated_total")
    )
    .filter(pl.col("calculated_total") != pl.col("Total"))
    .select(["year", "calculated_total", "Total"])
)

validation


plot_data = validation.to_dict(as_series=False)

(
    ggplot(plot_data, aes(x="year"))
    + geom_line(aes(y="calculated_total"), color="#1b6ca8", size=1.3)
    + geom_point(aes(y="calculated_total"), color="#1b6ca8", size=1.8)
    + geom_line(aes(y="Total"), color="#c0392b", size=1.3)
    + geom_point(aes(y="Total"), color="#c0392b", size=1.8)
    + labs(
        title="Validation of Total Babies Named David",
        x="Year",
        y="Count"
    )
    + theme_light()
)
```