---
title: "Client Report - Baseball Database"
subtitle: "Unit 3 Task 1"
author: "Mitzi Vite"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *
from IPython.display import display
LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

```{python}
# Include and execute your code here

# The code below uses some basic SQL code to read in the entire 'batting' table in the database and store it in a polars dataframe called 'results'. You must write polars code to manipulate the results dataframe to address the task.

q = """
    SELECT *
    FROM batting
    """
results = pl.read_database(q, con, infer_schema_length=None) 
# What does infer_schema_length = None do?
results
```

## QUESTION 1

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the number of at bats and the batting average for each year a player played. Filter the data frame to only include players with at least 10 at bats that year. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

The top 5 players with the highest batting average for a single season (with a minimum of 10 at bats) had very strong performances. Nymanny01 had the highest average at .643 in 1974, followed by carsoma01 with .636 in 2013. One thing I noticed is that all of these players had a relatively small number of at bats, between 10 and 16. 


```{python}
# Include and execute your code here
batting_avg_year = (results.group_by(["playerID", "yearID"])
  .agg([
    pl.sum("AB").alias("total_at_bats"),
    pl.sum("H").alias("total_hits"),
  ])
  .with_columns(
    (pl.col("total_hits") / pl.col("total_at_bats")).alias("batting_average")
  )
  .filter(pl.col("total_at_bats") >= 10)
  .sort(["batting_average", "playerID"], descending=[True, False])
  .head(5)
  )
display(batting_avg_year.to_pandas())
```


## QUESTION 2

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the batting average for each player over their entire career (all years combined). Only include players with at least 100 at bats over their entire career. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__ 

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

When looking at career batting averages with a minimum of 100 at bats, cobbty01 has the highest average at .366 over 11,436 at bats. Hornsro01 also had a very strong average of .358 across 8,173 at bats. These numbers are impressive because they show consistent performance over a long period of time.

I also noticed that none of the players from Question 1 appear in these results. This suggests that performing very well in a small number of at bats does not always mean a player will maintain that level of success throughout their career. Since this analysis uses much larger sample sizes, the results are more reliable.


```{python}
# Include and execute your code here
q2 = (results.group_by("playerID")
  .agg([
    pl.sum("AB").alias("total_at_bats"),
    pl.sum("H").alias("total_hits"),
  ])
  .with_columns(
    (pl.col("total_hits") / pl.col("total_at_bats")).alias("batting_average")
  )
  .filter(pl.col("total_at_bats") >= 100)
  .sort(["batting_average", "playerID"], descending=[True, False])
  .head(5)
  )
display(q2.to_pandas())
```


