---
title: "Client Report - Baseball Database SQL Query"
subtitle: "Unit 3 Task 2"
author: "Mitzi Vite"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

With a minimum of 1 at bat, the top 5 players all had a batting average of 1.0. This means they got a hit every time they were at bat. However, this can be misleading because a player with only one at bat and one hit will also have a perfect average. Because of this, it is important to use a larger minimum number of at bats to get more meaningful and reliable results.

```{python}
# Include and execute your code here

# The code below can serve as a template for all the rest of your queries. It is just missing the
# SQL code. Put your SQL query in between the triple quotation marks to create the query. The records will be stored in 'results', which is a polars data frame

q = """
  SELECT playerID, yearID, (CASE WHEN AB > 0 THEN H * 1.0 / AB ELSE NULL END) AS batting_average
  FROM batting
  WHERE AB >= 1
  ORDER BY batting_average DESC, playerID ASC
  LIMIT 5
    """
results = pl.read_database(q, con)
results


```


## QUESTION 2

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__  

After increasing the minimum to 10 at bats, the results look much more realistic. Nymanny01 has the highest batting average at .643 in 1974, followed by carsoma01 with .636 in 2013. No player reached a perfect 1.0 average, which shows that a higher minimum threshold helps produce more meaningful and reliable results.

```{python}
# Include and execute your code here

q = """
  SELECT playerID, yearID, (CASE WHEN AB > 0 THEN H * 1.0 / AB ELSE NULL END) AS batting_average
  FROM batting
  WHERE AB >= 10
  ORDER BY batting_average DESC, playerID ASC
  LIMIT 5
    """
results = pl.read_database(q, con)
results



```


## QUESTION 3

__Now modify the SQL query to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

When looking at entire careers with a minimum of 100 at bats, the batting averages are lower than in the previous questions. Cobbty01 has the highest average at .366, followed by barnero01 with .360. These results are more meaningful because they represent a player's performance over their entire career and not just one season.

It is also interesting that none of the players from the 10 at bat analysis appear in the career analysis. This shows that a player who performs very well in a short period of time may not maintain that same level of performance throughout their career. It also shows how much the sample size can affect the results.


```{python}
# Include and execute your code here
q = """
  SELECT playerID, (CASE WHEN SUM(AB) > 0 THEN SUM(H) * 1.0 / SUM(AB) ELSE NULL END) AS batting_average
  FROM batting
  GROUP BY playerID
  HAVING SUM(AB) >= 100
  ORDER BY batting_average DESC, playerID ASC
  LIMIT 5
    """
results = pl.read_database(q, con)
results
```
